[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test/'
cache_path  = 'forge-cache'
evm_version = "cancun"
# See more config options https://github.com/foundry-rs/foundry/tree/master/config

solc = "0.8.22"
optimizer = true
runs = 200
via-ir = true

rpc_endpoints = {baseSepolia="https://base-sepolia.gateway.tenderly.co", bscTestnet = "https://bsc-testnet.nodereal.io/v1/9a8b33a8518947ee9635b30b603f47ad", bsc = "https://rpc.ankr.com/bsc"}
